repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        # Make sure it targets the right files
        files: \.py$
      - id: ruff-format
        files: \.py$

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.10
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ["--branch", "develop", "--branch", "master"]
